---
sudo: false
language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-django111
    - python: 3.5
      env: TOXENV=py35-django111

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip

deps:
  - codecov

install:
  - pip install -U pip tox codecov

script:
  - tox -e $TOXENV

after_success:
  - tox -e coverage-report
  - codecov

notifications:
  email: false
